[package]
name = "rari-l10n"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rari-types = { path = "../rari-types" }
thiserror = "1"
serde_json = { version = "1", features = ["preserve_order"] }
