[package]
name = "rari-doc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
yaml-rust = "0.4"
percent-encoding = "2"
pest = "2"
pest_derive = "2"
regex = "1"
validator = { version = "0.18", features = ["derive"] }
once_cell = "1"
scraper = { version = "0.19", features = ["deterministic"] }
chrono = { version = "0.4", features = ["serde"] }
lol_html = "1"
html-escape = "0.2"
html5ever = "0.27"
tracing = "0.1"
ignore = "0.4"
crossbeam-channel = "0.5"
rayon = "1"
enum_dispatch = "0.3"
icu_collator = "1"
icu_locid = "1"
strum = { version = "0.26", features = ["derive"] }
ego-tree = "0.6"
url = "2"
imagesize = "0.13"
svg_metadata = "0.5"
itertools = "0.13"
memoize = "0.4"

rari-utils = { path = "../rari-utils" }
rari-types = { path = "../rari-types" }
rari-md = { path = "../rari-md" }
rari-data = { path = "../rari-data" }
rari-templ-func = { path = "../rari-templ-func" }
rari-l10n = { path = "../rari-l10n" }
css-syntax = { path = "../css-syntax", features = ["rari"] }

[dev-dependencies]
rari-types = { path = "../rari-types", features = ["testing"] }
