[package]
name = "rari-deps"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
once_cell = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
css-syntax-types = { path = "../css-syntax-types" }
rari-shared = { path = "../rari-shared" }
tar = "0.4"
flate2 = "1"
chrono = { version = "0.4", features = ["serde"] }
