[package]
name = "rari-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rari-types = { path = "../rari-types" }
rari-shared = { path = "../rari-shared" }
once_cell = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
csv = "1"
chrono = { version = "0.4", features = ["serde"] }
