[package]
name = "css-syntax"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = "1"
regress = "0.10"
serde_json = { version = "1", features = ["preserve_order"] }
serde = { version = "1", features = ["derive"] }
url = { version = "2", features = ["serde"] }
css-syntax-types = { path = "../css-syntax-types" }
css-definition-syntax = { path = "../css-definition-syntax" }
html-escape = "0.2"
rari-deps = { path = "../rari-deps" }
rari-types = { path = "../rari-types", optional = true }

[build-dependencies]
anyhow = "1"

[features]
default = []
rari = ["dep:rari-types"]
