[package]
name = "rari-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
testing = []
default = []

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_variant = "0.1"
serde_json = { version = "1", features = ["preserve_order"] }
normalize-path = "0.2"
strum = { version = "0.26", features = ["derive"] }
dirs = "5"
config = { version = "0.14", default-features = false, features = ["toml"] }
chrono = { version = "0.4", features = ["serde"] }
indexmap = { version = "2", features = ["serde"] }
