[package]
name = "rari-data"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rari-utils = { path = "../rari-utils" }
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
url = { version = "2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
indexmap = "2"
