[package]
name = "rari-md"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
base64 = "0.22"
regex = "1"
thiserror = "1"
comrak = { version = "0.26", default-features = false }
rari-types = { path = "../rari-types" }
itertools = "0.13"
